Controllers/MyController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using WebApplication2.Models;
using WebApplication2.Models.ViewModels;

namespace WebApplication2.Controllers
{
    public class MyController : Controller
    {
        // GET: My
        public ActionResult Index(QueryModel qmodel)
        {
            DbContext dbContext = new DbContext("NEWSEntities");
            List<News> newsList = dbContext.Set<News>().ToList();
            dbContext.Dispose();   // 类似于析构函数

            NewsListMessage newsListMessage = new NewsListMessage();
            if (string.IsNullOrEmpty(qmodel.key))
                newsListMessage.NewsList = newsList;
            else
                newsListMessage.NewsList = newsList.Where(o => o.Keyword.Contains(qmodel.key)).ToList();     

            return View(newsListMessage);
        }
        [HttpPost]
        public ActionResult Index(LoginModel loginmodel)
        {
            DbContext dbContext = new DbContext("NEWSEntities");
            List<News> newsList = dbContext.Set<News>().ToList();
            List<UserInfo> userInfoList = dbContext.Set<UserInfo>().ToList();
            dbContext.Dispose();   // 类似于析构函数

            NewsListMessage newsListMessage = new NewsListMessage();
            newsListMessage.NewsList = newsList;
            newsListMessage.CurrentUserName = loginmodel.iusername;

            ViewBag.NewsList = newsList;
            ViewBag.CurrentUserName = loginmodel.iusername;

            foreach (var item in userInfoList)
            {
                if(item.Nickname == loginmodel.iusername && item.Password == loginmodel.ipassword)
                {
                    return View(newsListMessage);
                } 
            }
            return View("~/Views/Home/Index.cshtml");
        }
        public ActionResult Add()
        {
            DbContext dbContext = new DbContext("NEWSEntities");
            List<NewsType> newsTypeList = dbContext.Set<NewsType>().ToList();
            dbContext.Dispose();   // 类似于析构函数
            ViewBag.newsTypeList = newsTypeList;

            return View();
        }
        [HttpPost]
        public ActionResult Add(News news)
        {
            DbContext dbContext = new DbContext("NEWSEntities");
            dbContext.Set<News>().Add(news);
            dbContext.SaveChanges();
            dbContext.Dispose();   // 类似于析构函数
            return View();
        }
        public ActionResult Modify(ModifyModel modifymodel)
        {
            DbContext dbContext = new DbContext("NEWSEntities");
            List<News> newsList = dbContext.Set<News>().ToList();
            newsList[modifymodel.Index].Title = modifymodel.Title;
            newsList[modifymodel.Index].Author = modifymodel.Author;
            newsList[modifymodel.Index].Keyword = modifymodel.Keyword;
            newsList[modifymodel.Index].Type = modifymodel.Type;
            dbContext.SaveChanges();
            dbContext.Dispose();

            NewsListMessage newsListMessage = new NewsListMessage();
            newsListMessage.NewsList = newsList;

            return View("~/Views/My/Index.cshtml", newsListMessage);
        }
        public ActionResult Delete(int Index)
        {
            DbContext dbContext = new DbContext("NEWSEntities");
            List<News> newsList = dbContext.Set<News>().ToList();
            //newsList.Remove(newsList[Index]);
            //News news = dbContext.Set<News>().Find(Index);
            dbContext.Set<News>().Remove(newsList[Index]);
            dbContext.SaveChanges();

            NewsListMessage newsListMessage = new NewsListMessage();
            newsListMessage.NewsList = newsList;
            newsList = dbContext.Set<News>().ToList();
            dbContext.Dispose();

            return View("~/Views/My/Index.cshtml", newsListMessage);
        }
        public ActionResult Details()
        {
            ViewBag.Message = "我是分部视图";

            return PartialView();
        }
    }
}

Views/Shared/_ClientLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    @*<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">*@
    <title>广西新闻</title>

    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content//nav.css">
</head>
<body>
    <nav id="myNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">NEWS</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li v-bind:class="flag? 'active' : ''" v-on:click="isActive"><a href="#">新闻资讯</a></li>
                    <li v-bind:class="!flag? 'active' : ''" v-on:click="isActive"><a href="#">分类</a></li>
                </ul>
                <form class="navbar-form navbar-right">
                    <div class="form-group">
                        <div class="input-group input-group-lg">
                            <input type="text" class="form-control" placeholder="Search">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
                            </span>
                        </div>
                    </div>
                </form>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
        <!-- 二级菜单 -->
        <div v-bind:class="flag? 'wrap' : 'wrap on'">
            <ul>
                <li><a href="">国际</a></li>
                <li><a href="">政治</a></li>
                <li><a href="">军事</a></li>
                <li><a href="">科技</a></li>
                <li><a href="">娱乐</a></li>
                <li><a href="">其他</a></li>
            </ul>
        </div>
    </nav>

    <main class="container">
        @RenderBody()
    </main>
    <script src="~/Scripts/vue.js"></script>
    <script>
			new Vue({
				el: '#myNav',
				data: {
					flag: true
				},
				methods: {
					isActive() {
						this.flag = !this.flag;
					}
				}
			})
    </script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>新闻管理 - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("新闻管理系统", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                    <li>@Html.ActionLink("管理", "Index", "My")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 新闻管理系统</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>